### ISSUE TITLE
Error on docker container

### ISSUE THREAD

**Issue by ghost** [Mapotempo/optimizer-api#1]
optimizer_1       | [ E 2018-05-23 13:06:16.8901 10/Ti age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /srv/app: The application encountered the following error: undefined local variable or method `server' for #<Rack::Builder:0x005569e292e7c0 @run=nil, @map=nil, @use=[]> (NameError)

it runs without errors but on optimizing reques it fails and gives back an html back and this error

**Comment by frodrigo** [comment]
Do you have more logs ?

**Comment by johnGarcia123** [comment]
sems like passenger crashes

**Comment by johnGarcia123** [comment]
redis-cache_1     | 1:M 25 May 11:05:20.884 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis-cache_1     | 1:M 25 May 11:05:20.884 # Server started, Redis version 3.2.11
redis-cache_1     | 1:M 25 May 11:05:20.884 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis-cache_1     | 1:M 25 May 11:05:20.884 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis-cache_1     | 1:M 25 May 11:05:20.884 * The server is now ready to accept connections on port 6379
optimizer_1       | [ N 2018-05-25 11:05:29.1745 7/T1 age/Wat/WatchdogMain.cpp:1259 ]: Starting Passenger watchdog...
optimizer_1       | [ N 2018-05-25 11:05:29.3008 10/T1 age/Cor/CoreMain.cpp:1236 ]: Starting Passenger core...
optimizer_1       | [ N 2018-05-25 11:05:29.3242 10/T1 age/Cor/CoreMain.cpp:251 ]: Passenger core running in multi-application mode.
optimizer_1       | [ N 2018-05-25 11:05:29.3599 10/T1 age/Cor/CoreMain.cpp:971 ]: Passenger core online, PID 10
optimizer_1       | [ N 2018-05-25 11:05:31.6493 10/T5 age/Cor/SecurityUpdateChecker.h:517 ]: Security update check: no update found (next check in 24 hours)
optimizer_1       | App 164 output: Error: The application encountered the following error: undefined local variable or method `server' for #<Rack::Builder:0x00562e276d6658 @run=nil, @map=nil, @use=[]> (NameError)
optimizer_1       | App 164 output:     config.ru:1:in `block in <main>'
optimizer_1       | App 164 output:     /var/lib/gems/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
optimizer_1       | App 164 output:     /var/lib/gems/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
optimizer_1       | App 164 output:     config.ru:1:in `new'
optimizer_1       | App 164 output:     config.ru:1:in `<main>'
optimizer_1       | App 164 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
optimizer_1       | App 164 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
optimizer_1       | App 164 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
optimizer_1       | App 164 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
optimizer_1       | App 164 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
optimizer_1       | App 164 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
optimizer_1       | App 164 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
optimizer_1       | [ E 2018-05-25 11:09:23.0680 10/Ti age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /srv/app: The application encountered the following error: undefined local variable or method `server' for #<Rack::Builder:0x00562e276d6658 @run=nil, @map=nil, @use=[]> (NameError)
optimizer_1       |   Error ID: cb968664
optimizer_1       |   Error details saved to: /tmp/passenger-error-G6lEdf.html
optimizer_1       | 
optimizer_1       | [ E 2018-05-25 11:09:23.0709 10/T8 age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is cb968664. Please see earlier logs for details about the error.
optimizer_1       | 2018/05/25 11:09:23 [error] 19#19: *1 recv() failed (104: Connection reset by peer) while sending to client, client: ::ffff:192.168.0.1, server: , request: "POST /0.1/vrp/submit.json HTTP/1.1", upstream: "passenger:unix:/tmp/passenger.kshteOQ/agents.s/core:", host: "192.168.0.1:8083"
optimizer_1       | ::ffff:192.168.0.1 - - [25/May/2018:11:09:23 +0000] "POST /0.1/vrp/submit.json HTTP/1.1" 500 4384 "-" "rest-client/2.0.2 (linux-gnu x86_64) ruby/2.4.1p111"
optimizer_1       | App 208 output: Error: The application encountered the following error: undefined local variable or method `server' for #<Rack::Builder:0x005592b8b1be80 @run=nil, @map=nil, @use=[]> (NameError)
optimizer_1       | App 208 output:     config.ru:1:in `block in <main>'
optimizer_1       | App 208 output:     /var/lib/gems/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
optimizer_1       | App 208 output:     /var/lib/gems/2.3.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
optimizer_1       | App 208 output:     config.ru:1:in `new'
optimizer_1       | App 208 output:     config.ru:1:in `<main>'
optimizer_1       | App 208 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
optimizer_1       | App 208 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
optimizer_1       | App 208 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
optimizer_1       | App 208 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
optimizer_1       | App 208 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
optimizer_1       | App 208 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
optimizer_1       | App 208 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
optimizer_1       | [ E 2018-05-25 11:09:47.7260 10/Tn age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /srv/app: The application encountered the following error: undefined local variable or method `server' for #<Rack::Builder:0x005592b8b1be80 @run=nil, @map=nil, @use=[]> (NameError)
optimizer_1       |   Error ID: 85be73f3
optimizer_1       |   Error details saved to: /tmp/passenger-error-HkG0cy.html

**Comment by johnGarcia123** [comment]
Any solution?

**Comment by braktar** [comment]
Are those logs coming from Mapotempo Web ? Did you try to send a problem directly to the optimizer-api ?

**Comment by johnGarcia123** [comment]
yes i try.. the second log is from mapotempo web ..

**Comment by johnGarcia123** [comment]
i cant resolve this error. it gives me the same.. does optimizer api needs osrm inside the machine and maybe vroom does not find default instance for osrm?
